version: '3'
services:
    web:
        build:
          context: .
          dockerfile: ./docker/Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        links:
            - db
        depends_on:
            - db
    db:
        image: "postgres:10.9"
        ports:
            - "5432:5432"


